### PR TITLE
For Laravel 7

### PR DESCRIPTION
**Pull request by samueljohnw**
Currently doesn't work when setting up L7.

### CODE REVIEW

**Comment by samueljohnw** [comment]
PLease update the composer file so bulma preset will work with L7

**Comment by mikeerickson** [comment]
Any chance this PR gets merged in the near future so we can use with Laravel 7?

**Comment by mikeerickson** [comment]
@samueljohnw Was this all that is required so that it can work with Laravel 7?
Where you able to get it installed manually and have a working solution?

**Comment by robertgarrigos** [comment]
Actually, it doesn't work:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class 'Illuminate\Foundation\Console\PresetCommand' not found

  at packages/laravel-frontend-presets/bulma/src/BulmaPresetServiceProvider.php:16
    12|      * @return void
    13|      */
    14|     public function boot()
    15|     {
  > 16|         PresetCommand::macro('bulma', function ($command) {
    17|             BulmaPreset::install(false);
    18|             $command->info('Bulma scaffolding installed successfully.');
    19|             $command->comment('Please run "npm install && npm run dev" to compile your fresh scaffolding.');
    20|         });

      +8 vendor frames 
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(LaravelFrontendPresets\BulmaPreset\BulmaPresetServiceProvider))

      +5 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by robertgarrigos** [comment]
mmm well, it's NOT working

**Pull request merged**
